spring:
  datasource:
    url: jdbc:postgresql://postgres-service:5432/sopfc
    username: user
    password: password
  flyway:
    enabled: false # Desactivado temporalmente para bypass de checksums
  jpa:
    hibernate:
      ddl-auto: update # Permitir que Hibernate aplique los cambios del modelo (V4)
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect

apple:
  sentinel:
    # URL de tu Mac Mini en la VPN de Tailscale
    url: https://mac-mini-de-daniel.tail95d990.ts.net

logging:
  level:
    com.hyperbrain.sopfc: INFO
    org.springframework.web: WARN
